services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
    hostname: ${COMPOSE_PROJECT_NAME}-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${COMPOSE_PROJECT_NAME}
      RABBITMQ_DEFAULT_PASS: YsolXeGRA8ou
    networks:
      internal:
        aliases:
          - rabbitmq.internal
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 10

networks:
  internal: {}

volumes:
  rabbitmq:
    name: ${COMPOSE_PROJECT_NAME}-rabbitmq
