services:
  php:
    build:
      context: php
      target: dev
    hostname: ${COMPOSE_PROJECT_NAME}-php
    container_name: ${COMPOSE_PROJECT_NAME}-php
    user: user
    volumes:
      - /home/alex/.local/share/mkcert:/usr/local/share/ca-certificates/
      - ./php/php-ext-curl.ini:/usr/local/etc/php/conf.d/php-ext-curl.ini
    environment:
      - SSL_CERT_FILE=/usr/local/share/ca-certificates/rootCA.pem
    networks:
      internal:
        aliases:
          - php.internal

networks:
  internal: {}