services:
  php:
    environment:
      - "XDEBUG_CONFIG=client_host=host.docker.internal log_level=0"
      - "XDEBUG_MODE=debug,develop"
      - "XDEBUG_SESSION=1"
      - "PHP_IDE_CONFIG=serverName=parser-service"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./..:/data
    restart: "no"
    networks:
      internal: {}
