services:
  novnc:
    image: theasp/novnc:latest
    container_name: ${COMPOSE_PROJECT_NAME}-novnc
    hostname: ${COMPOSE_PROJECT_NAME}-novnc
    ports:
      - 8080:8080
    networks:
      internal:
        aliases:
          - novnc.internal
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no

networks:
  internal: {}
